/*

    OpenGL loader generated by glad 0.1.18a0 on Sat Apr 14 23:32:27 2018.

    Language/Generator: C/C++
    Specification: gl
    APIs: gl=3.2
    Profile: core
    Extensions:
        
    Loader: True
    Local files: True
    Omit khrplatform: True

    Commandline:
        --profile="core" --api="gl=3.2" --generator="c" --spec="gl" --local-files --omit-khrplatform --extensions=""
    Online:
        http://glad.dav1d.de/#profile=core&language=c&specification=gl&loader=on&api=gl%3D3.2
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "xwfglad.h"

static void* get_proc(const char *namez);

#ifdef _WIN32
#include <windows.h>
static HMODULE libGL;

typedef void* (APIENTRYP PFNWGLGETPROCADDRESSPROC_PRIVATE)(const char*);
static PFNWGLGETPROCADDRESSPROC_PRIVATE xwfglGetProcAddressPtr;

static
int open_gl(void) {
    libGL = LoadLibraryW(L"opengl32.dll");
    if(libGL != NULL) {
        xwfglGetProcAddressPtr = (PFNWGLGETPROCADDRESSPROC_PRIVATE)GetProcAddress(
                libGL, "wglGetProcAddress");
        return xwfglGetProcAddressPtr != NULL;
    }

    return 0;
}

static
void close_gl(void) {
    if(libGL != NULL) {
        FreeLibrary((HMODULE) libGL);
    libGL = NULL;
    }
}
#else
#include <dlfcn.h>
static void* libGL;

#ifndef __APPLE__
typedef void* (APIENTRYP PFNGLXGETPROCADDRESSPROC_PRIVATE)(const char*);
static PFNGLXGETPROCADDRESSPROC_PRIVATE xwfglGetProcAddressPtr;
#endif

static
int open_gl(void) {
#ifdef __APPLE__
    static const char *NAMES[] = {
        "../Frameworks/OpenGL.framework/OpenGL",
        "/Library/Frameworks/OpenGL.framework/OpenGL",
        "/System/Library/Frameworks/OpenGL.framework/OpenGL",
        "/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL"
    };
#else
    static const char *NAMES[] = {"libGL.so.1", "libGL.so"};
#endif

    unsigned int index = 0;
    for(index = 0; index < (sizeof(NAMES) / sizeof(NAMES[0])); index++) {
        libGL = dlopen(NAMES[index], RTLD_NOW | RTLD_GLOBAL);

        if(libGL != NULL) {
#ifdef __APPLE__
            return 1;
#else
            xwfglGetProcAddressPtr = (PFNGLXGETPROCADDRESSPROC_PRIVATE)dlsym(libGL,
                "glXGetProcAddressARB");
            return xwfglGetProcAddressPtr != NULL;
#endif
        }
    }

    return 0;
}

static
void close_gl(void) {
    if(libGL != NULL) {
        dlclose(libGL);
        libGL = NULL;
    }
}
#endif

static
void* get_proc(const char *namez) {
    void* result = NULL;
    if(libGL == NULL) return NULL;

#ifndef __APPLE__
    if(xwfglGetProcAddressPtr != NULL) {
        result = xwfglGetProcAddressPtr(namez);
    }
#endif
    if(result == NULL) {
#ifdef _WIN32
        result = (void*)GetProcAddress((HMODULE) libGL, namez);
#else
        result = dlsym(libGL, namez);
#endif
    }

    return result;
}

int xwfglLoadGL(void) {
    int status = 0;

    if(open_gl()) {
        status = xwfglLoadGLLoader(&get_proc);
        close_gl();
    }

    return status;
}

struct xwfglGLversionStruct GLVersion;

#if defined(GL_ES_VERSION_3_0) || defined(GL_VERSION_3_0)
#define _XWFGL_IS_SOME_NEW_VERSION 1
#endif

static int max_loaded_major;
static int max_loaded_minor;

static const char *exts = NULL;
static int num_exts_i = 0;
static const char **exts_i = NULL;

static int get_exts(void) {
#ifdef _XWFGL_IS_SOME_NEW_VERSION
    if(max_loaded_major < 3) {
#endif
        exts = (const char *)glGetString(GL_EXTENSIONS);
#ifdef _XWFGL_IS_SOME_NEW_VERSION
    } else {
        unsigned int index;

        num_exts_i = 0;
        glGetIntegerv(GL_NUM_EXTENSIONS, &num_exts_i);
        if (num_exts_i > 0) {
            exts_i = (const char **)realloc((void *)exts_i, (size_t)num_exts_i * (sizeof *exts_i));
        }

        if (exts_i == NULL) {
            return 0;
        }

        for(index = 0; index < (unsigned)num_exts_i; index++) {
            const char *gl_str_tmp = (const char*)glGetStringi(GL_EXTENSIONS, index);
            size_t len = strlen(gl_str_tmp);

            char *local_str = (char*)malloc((len+1) * sizeof(char));
            if(local_str != NULL) {
#if _MSC_VER >= 1400
                strncpy_s(local_str, len+1, gl_str_tmp, len);
#else
                strncpy(local_str, gl_str_tmp, len+1);
#endif
            }
            exts_i[index] = local_str;
        }
    }
#endif
    return 1;
}

static void free_exts(void) {
    if (exts_i != NULL) {
        int index;
        for(index = 0; index < num_exts_i; index++) {
            free((char *)exts_i[index]);
        }
        free((void *)exts_i);
        exts_i = NULL;
    }
}

static int has_ext(const char *ext) {
#ifdef _XWFGL_IS_SOME_NEW_VERSION
    if(max_loaded_major < 3) {
#endif
        const char *extensions;
        const char *loc;
        const char *terminator;
        extensions = exts;
        if(extensions == NULL || ext == NULL) {
            return 0;
        }

        while(1) {
            loc = strstr(extensions, ext);
            if(loc == NULL) {
                return 0;
            }

            terminator = loc + strlen(ext);
            if((loc == extensions || *(loc - 1) == ' ') &&
                (*terminator == ' ' || *terminator == '\0')) {
                return 1;
            }
            extensions = terminator;
        }
#ifdef _XWFGL_IS_SOME_NEW_VERSION
    } else {
        int index;
        if(exts_i == NULL) return 0;
        for(index = 0; index < num_exts_i; index++) {
            const char *e = exts_i[index];

            if(exts_i[index] != NULL && strcmp(e, ext) == 0) {
                return 1;
            }
        }
    }
#endif

    return 0;
}
int XWFGL_GL_VERSION_1_0;
int XWFGL_GL_VERSION_1_1;
int XWFGL_GL_VERSION_1_2;
int XWFGL_GL_VERSION_1_3;
int XWFGL_GL_VERSION_1_4;
int XWFGL_GL_VERSION_1_5;
int XWFGL_GL_VERSION_2_0;
int XWFGL_GL_VERSION_2_1;
int XWFGL_GL_VERSION_3_0;
int XWFGL_GL_VERSION_3_1;
int XWFGL_GL_VERSION_3_2;
PFNGLDELETEVERTEXARRAYSPROC xwfgl_glDeleteVertexArrays;
PFNGLBEGINTRANSFORMFEEDBACKPROC xwfgl_glBeginTransformFeedback;
PFNGLFLUSHPROC xwfgl_glFlush;
PFNGLCOPYTEXIMAGE1DPROC xwfgl_glCopyTexImage1D;
PFNGLCLEARCOLORPROC xwfgl_glClearColor;
PFNGLVERTEXATTRIBI3UIPROC xwfgl_glVertexAttribI3ui;
PFNGLGETUNIFORMBLOCKINDEXPROC xwfgl_glGetUniformBlockIndex;
PFNGLVERTEXATTRIB4NIVPROC xwfgl_glVertexAttrib4Niv;
PFNGLCLEARBUFFERIVPROC xwfgl_glClearBufferiv;
PFNGLSTENCILMASKSEPARATEPROC xwfgl_glStencilMaskSeparate;
PFNGLGETVERTEXATTRIBPOINTERVPROC xwfgl_glGetVertexAttribPointerv;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC xwfgl_glGetFramebufferAttachmentParameteriv;
PFNGLBINDFRAGDATALOCATIONPROC xwfgl_glBindFragDataLocation;
PFNGLLINKPROGRAMPROC xwfgl_glLinkProgram;
PFNGLBINDTEXTUREPROC xwfgl_glBindTexture;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC xwfgl_glGetActiveUniformBlockName;
PFNGLVERTEXATTRIBI2UIVPROC xwfgl_glVertexAttribI2uiv;
PFNGLFENCESYNCPROC xwfgl_glFenceSync;
PFNGLUNIFORM3UIPROC xwfgl_glUniform3ui;
PFNGLUNIFORM2UIVPROC xwfgl_glUniform2uiv;
PFNGLGETSTRINGPROC xwfgl_glGetString;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC xwfgl_glCompressedTexSubImage3D;
PFNGLDETACHSHADERPROC xwfgl_glDetachShader;
PFNGLVERTEXATTRIBI4UIVPROC xwfgl_glVertexAttribI4uiv;
PFNGLGENBUFFERSPROC xwfgl_glGenBuffers;
PFNGLENDQUERYPROC xwfgl_glEndQuery;
PFNGLPOINTPARAMETERFVPROC xwfgl_glPointParameterfv;
PFNGLLINEWIDTHPROC xwfgl_glLineWidth;
PFNGLUNIFORM2FVPROC xwfgl_glUniform2fv;
PFNGLDRAWELEMENTSINSTANCEDPROC xwfgl_glDrawElementsInstanced;
PFNGLGETINTEGERI_VPROC xwfgl_glGetIntegeri_v;
PFNGLBINDATTRIBLOCATIONPROC xwfgl_glBindAttribLocation;
PFNGLCOMPILESHADERPROC xwfgl_glCompileShader;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC xwfgl_glGetTransformFeedbackVarying;
PFNGLDELETETEXTURESPROC xwfgl_glDeleteTextures;
PFNGLSTENCILOPSEPARATEPROC xwfgl_glStencilOpSeparate;
PFNGLUNIFORMMATRIX3FVPROC xwfgl_glUniformMatrix3fv;
PFNGLPOLYGONMODEPROC xwfgl_glPolygonMode;
PFNGLBINDBUFFERRANGEPROC xwfgl_glBindBufferRange;
PFNGLVERTEXATTRIB4FPROC xwfgl_glVertexAttrib4f;
PFNGLGENRENDERBUFFERSPROC xwfgl_glGenRenderbuffers;
PFNGLVERTEXATTRIB4DPROC xwfgl_glVertexAttrib4d;
PFNGLVERTEXATTRIB1FPROC xwfgl_glVertexAttrib1f;
PFNGLGETBUFFERPARAMETERI64VPROC xwfgl_glGetBufferParameteri64v;
PFNGLISSYNCPROC xwfgl_glIsSync;
PFNGLCLAMPCOLORPROC xwfgl_glClampColor;
PFNGLUNIFORM4IVPROC xwfgl_glUniform4iv;
PFNGLGETTEXPARAMETERIVPROC xwfgl_glGetTexParameteriv;
PFNGLCLEARSTENCILPROC xwfgl_glClearStencil;
PFNGLFRAMEBUFFERTEXTUREPROC xwfgl_glFramebufferTexture;
PFNGLUNIFORMMATRIX2X3FVPROC xwfgl_glUniformMatrix2x3fv;
PFNGLVERTEXATTRIB4SPROC xwfgl_glVertexAttrib4s;
PFNGLDRAWELEMENTSBASEVERTEXPROC xwfgl_glDrawElementsBaseVertex;
PFNGLGETVERTEXATTRIBIUIVPROC xwfgl_glGetVertexAttribIuiv;
PFNGLENABLEIPROC xwfgl_glEnablei;
PFNGLSAMPLECOVERAGEPROC xwfgl_glSampleCoverage;
PFNGLVERTEXATTRIB4NUSVPROC xwfgl_glVertexAttrib4Nusv;
PFNGLGENTEXTURESPROC xwfgl_glGenTextures;
PFNGLDEPTHFUNCPROC xwfgl_glDepthFunc;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC xwfgl_glCompressedTexSubImage2D;
PFNGLGETRENDERBUFFERPARAMETERIVPROC xwfgl_glGetRenderbufferParameteriv;
PFNGLUNIFORM1FPROC xwfgl_glUniform1f;
PFNGLGETVERTEXATTRIBFVPROC xwfgl_glGetVertexAttribfv;
PFNGLVERTEXATTRIBI4BVPROC xwfgl_glVertexAttribI4bv;
PFNGLVERTEXATTRIB4NBVPROC xwfgl_glVertexAttrib4Nbv;
PFNGLGETTEXPARAMETERFVPROC xwfgl_glGetTexParameterfv;
PFNGLGETCOMPRESSEDTEXIMAGEPROC xwfgl_glGetCompressedTexImage;
PFNGLISVERTEXARRAYPROC xwfgl_glIsVertexArray;
PFNGLCREATESHADERPROC xwfgl_glCreateShader;
PFNGLISBUFFERPROC xwfgl_glIsBuffer;
PFNGLUNIFORM1IPROC xwfgl_glUniform1i;
PFNGLVERTEXATTRIB3SPROC xwfgl_glVertexAttrib3s;
PFNGLGETACTIVEATTRIBPROC xwfgl_glGetActiveAttrib;
PFNGLCOPYTEXSUBIMAGE2DPROC xwfgl_glCopyTexSubImage2D;
PFNGLVERTEXATTRIB3DVPROC xwfgl_glVertexAttrib3dv;
PFNGLTEXSUBIMAGE2DPROC xwfgl_glTexSubImage2D;
PFNGLDISABLEPROC xwfgl_glDisable;
PFNGLUNIFORM2IPROC xwfgl_glUniform2i;
PFNGLBLENDFUNCSEPARATEPROC xwfgl_glBlendFuncSeparate;
PFNGLLOGICOPPROC xwfgl_glLogicOp;
PFNGLVERTEXATTRIBI4SVPROC xwfgl_glVertexAttribI4sv;
PFNGLGETPROGRAMIVPROC xwfgl_glGetProgramiv;
PFNGLCOLORMASKPROC xwfgl_glColorMask;
PFNGLHINTPROC xwfgl_glHint;
PFNGLVERTEXATTRIB1SPROC xwfgl_glVertexAttrib1s;
PFNGLFRAMEBUFFERTEXTURELAYERPROC xwfgl_glFramebufferTextureLayer;
PFNGLTEXPARAMETERIIVPROC xwfgl_glTexParameterIiv;
PFNGLBLENDEQUATIONPROC xwfgl_glBlendEquation;
PFNGLGETUNIFORMLOCATIONPROC xwfgl_glGetUniformLocation;
PFNGLSAMPLEMASKIPROC xwfgl_glSampleMaski;
PFNGLBINDFRAMEBUFFERPROC xwfgl_glBindFramebuffer;
PFNGLENDTRANSFORMFEEDBACKPROC xwfgl_glEndTransformFeedback;
PFNGLCULLFACEPROC xwfgl_glCullFace;
PFNGLUNIFORMMATRIX3X2FVPROC xwfgl_glUniformMatrix3x2fv;
PFNGLVERTEXATTRIB4USVPROC xwfgl_glVertexAttrib4usv;
PFNGLUNIFORM4FVPROC xwfgl_glUniform4fv;
PFNGLGETTEXPARAMETERIUIVPROC xwfgl_glGetTexParameterIuiv;
PFNGLDELETEFRAMEBUFFERSPROC xwfgl_glDeleteFramebuffers;
PFNGLUNIFORM1UIVPROC xwfgl_glUniform1uiv;
PFNGLPOINTSIZEPROC xwfgl_glPointSize;
PFNGLGETSTRINGIPROC xwfgl_glGetStringi;
PFNGLVERTEXATTRIB2DVPROC xwfgl_glVertexAttrib2dv;
PFNGLVERTEXATTRIBI1IVPROC xwfgl_glVertexAttribI1iv;
PFNGLDELETEPROGRAMPROC xwfgl_glDeleteProgram;
PFNGLVERTEXATTRIB4NUIVPROC xwfgl_glVertexAttrib4Nuiv;
PFNGLGENQUERIESPROC xwfgl_glGenQueries;
PFNGLWAITSYNCPROC xwfgl_glWaitSync;
PFNGLATTACHSHADERPROC xwfgl_glAttachShader;
PFNGLBLITFRAMEBUFFERPROC xwfgl_glBlitFramebuffer;
PFNGLRENDERBUFFERSTORAGEPROC xwfgl_glRenderbufferStorage;
PFNGLUNIFORMMATRIX4X3FVPROC xwfgl_glUniformMatrix4x3fv;
PFNGLUNIFORM3IPROC xwfgl_glUniform3i;
PFNGLCOMPRESSEDTEXIMAGE1DPROC xwfgl_glCompressedTexImage1D;
PFNGLCOPYTEXSUBIMAGE1DPROC xwfgl_glCopyTexSubImage1D;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC xwfgl_glDrawRangeElementsBaseVertex;
PFNGLCHECKFRAMEBUFFERSTATUSPROC xwfgl_glCheckFramebufferStatus;
PFNGLTEXSUBIMAGE3DPROC xwfgl_glTexSubImage3D;
PFNGLGETINTEGER64I_VPROC xwfgl_glGetInteger64i_v;
PFNGLPROVOKINGVERTEXPROC xwfgl_glProvokingVertex;
PFNGLGETMULTISAMPLEFVPROC xwfgl_glGetMultisamplefv;
PFNGLCOPYTEXIMAGE2DPROC xwfgl_glCopyTexImage2D;
PFNGLUNIFORM3FPROC xwfgl_glUniform3f;
PFNGLVERTEXATTRIB4UBVPROC xwfgl_glVertexAttrib4ubv;
PFNGLGETBUFFERPARAMETERIVPROC xwfgl_glGetBufferParameteriv;
PFNGLUNIFORMMATRIX4X2FVPROC xwfgl_glUniformMatrix4x2fv;
PFNGLENDCONDITIONALRENDERPROC xwfgl_glEndConditionalRender;
PFNGLDRAWELEMENTSPROC xwfgl_glDrawElements;
PFNGLCOLORMASKIPROC xwfgl_glColorMaski;
PFNGLISENABLEDIPROC xwfgl_glIsEnabledi;
PFNGLVERTEXATTRIB1DVPROC xwfgl_glVertexAttrib1dv;
PFNGLDRAWRANGEELEMENTSPROC xwfgl_glDrawRangeElements;
PFNGLGETQUERYOBJECTUIVPROC xwfgl_glGetQueryObjectuiv;
PFNGLGENVERTEXARRAYSPROC xwfgl_glGenVertexArrays;
PFNGLBINDBUFFERBASEPROC xwfgl_glBindBufferBase;
PFNGLBUFFERSUBDATAPROC xwfgl_glBufferSubData;
PFNGLUNIFORM1IVPROC xwfgl_glUniform1iv;
PFNGLGETQUERYOBJECTIVPROC xwfgl_glGetQueryObjectiv;
PFNGLUNIFORM4UIVPROC xwfgl_glUniform4uiv;
PFNGLREADBUFFERPROC xwfgl_glReadBuffer;
PFNGLCOPYBUFFERSUBDATAPROC xwfgl_glCopyBufferSubData;
PFNGLBINDVERTEXARRAYPROC xwfgl_glBindVertexArray;
PFNGLCLIENTWAITSYNCPROC xwfgl_glClientWaitSync;
PFNGLBEGINCONDITIONALRENDERPROC xwfgl_glBeginConditionalRender;
PFNGLVERTEXATTRIB3SVPROC xwfgl_glVertexAttrib3sv;
PFNGLVERTEXATTRIBI2UIPROC xwfgl_glVertexAttribI2ui;
PFNGLGENERATEMIPMAPPROC xwfgl_glGenerateMipmap;
PFNGLMULTIDRAWARRAYSPROC xwfgl_glMultiDrawArrays;
PFNGLFRAMEBUFFERTEXTURE1DPROC xwfgl_glFramebufferTexture1D;
PFNGLGETSHADERIVPROC xwfgl_glGetShaderiv;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC xwfgl_glGetActiveUniformBlockiv;
PFNGLUNIFORMMATRIX3X4FVPROC xwfgl_glUniformMatrix3x4fv;
PFNGLVERTEXATTRIB3FPROC xwfgl_glVertexAttrib3f;
PFNGLVERTEXATTRIB4UIVPROC xwfgl_glVertexAttrib4uiv;
PFNGLPOINTPARAMETERIPROC xwfgl_glPointParameteri;
PFNGLBLENDCOLORPROC xwfgl_glBlendColor;
PFNGLENABLEVERTEXATTRIBARRAYPROC xwfgl_glEnableVertexAttribArray;
PFNGLUNMAPBUFFERPROC xwfgl_glUnmapBuffer;
PFNGLDEPTHMASKPROC xwfgl_glDepthMask;
PFNGLPOINTPARAMETERFPROC xwfgl_glPointParameterf;
PFNGLDISABLEIPROC xwfgl_glDisablei;
PFNGLGETDOUBLEVPROC xwfgl_glGetDoublev;
PFNGLVERTEXATTRIBI4IVPROC xwfgl_glVertexAttribI4iv;
PFNGLVERTEXATTRIB1SVPROC xwfgl_glVertexAttrib1sv;
PFNGLSHADERSOURCEPROC xwfgl_glShaderSource;
PFNGLBINDRENDERBUFFERPROC xwfgl_glBindRenderbuffer;
PFNGLCOMPRESSEDTEXIMAGE2DPROC xwfgl_glCompressedTexImage2D;
PFNGLVERTEXATTRIBI3UIVPROC xwfgl_glVertexAttribI3uiv;
PFNGLVERTEXATTRIBI2IVPROC xwfgl_glVertexAttribI2iv;
PFNGLDRAWARRAYSPROC xwfgl_glDrawArrays;
PFNGLUNIFORM1UIPROC xwfgl_glUniform1ui;
PFNGLISPROGRAMPROC xwfgl_glIsProgram;
PFNGLGETTEXLEVELPARAMETERIVPROC xwfgl_glGetTexLevelParameteriv;
PFNGLGETFRAGDATALOCATIONPROC xwfgl_glGetFragDataLocation;
PFNGLGETSYNCIVPROC xwfgl_glGetSynciv;
PFNGLGETUNIFORMIVPROC xwfgl_glGetUniformiv;
PFNGLVERTEXATTRIBI2IPROC xwfgl_glVertexAttribI2i;
PFNGLUNIFORM4IPROC xwfgl_glUniform4i;
PFNGLVERTEXATTRIB3DPROC xwfgl_glVertexAttrib3d;
PFNGLCLEARPROC xwfgl_glClear;
PFNGLVERTEXATTRIB4FVPROC xwfgl_glVertexAttrib4fv;
PFNGLGETACTIVEUNIFORMNAMEPROC xwfgl_glGetActiveUniformName;
PFNGLUNIFORM2FPROC xwfgl_glUniform2f;
PFNGLTEXIMAGE2DMULTISAMPLEPROC xwfgl_glTexImage2DMultisample;
PFNGLACTIVETEXTUREPROC xwfgl_glActiveTexture;
PFNGLBEGINQUERYPROC xwfgl_glBeginQuery;
PFNGLUNIFORM2IVPROC xwfgl_glUniform2iv;
PFNGLBINDBUFFERPROC xwfgl_glBindBuffer;
PFNGLISENABLEDPROC xwfgl_glIsEnabled;
PFNGLSTENCILOPPROC xwfgl_glStencilOp;
PFNGLREADPIXELSPROC xwfgl_glReadPixels;
PFNGLCLEARDEPTHPROC xwfgl_glClearDepth;
PFNGLVERTEXATTRIBI3IVPROC xwfgl_glVertexAttribI3iv;
PFNGLUNIFORM4FPROC xwfgl_glUniform4f;
PFNGLFRAMEBUFFERTEXTURE2DPROC xwfgl_glFramebufferTexture2D;
PFNGLMAPBUFFERPROC xwfgl_glMapBuffer;
PFNGLVERTEXATTRIB1DPROC xwfgl_glVertexAttrib1d;
PFNGLVERTEXATTRIB4NUBPROC xwfgl_glVertexAttrib4Nub;
PFNGLUNIFORM3FVPROC xwfgl_glUniform3fv;
PFNGLGETUNIFORMFVPROC xwfgl_glGetUniformfv;
PFNGLBUFFERDATAPROC xwfgl_glBufferData;
PFNGLGETTEXPARAMETERIIVPROC xwfgl_glGetTexParameterIiv;
PFNGLCOMPRESSEDTEXIMAGE3DPROC xwfgl_glCompressedTexImage3D;
PFNGLTEXIMAGE1DPROC xwfgl_glTexImage1D;
PFNGLDELETESYNCPROC xwfgl_glDeleteSync;
PFNGLCOPYTEXSUBIMAGE3DPROC xwfgl_glCopyTexSubImage3D;
PFNGLGETERRORPROC xwfgl_glGetError;
PFNGLDELETERENDERBUFFERSPROC xwfgl_glDeleteRenderbuffers;
PFNGLGETVERTEXATTRIBIVPROC xwfgl_glGetVertexAttribiv;
PFNGLTEXPARAMETERIVPROC xwfgl_glTexParameteriv;
PFNGLMULTIDRAWELEMENTSPROC xwfgl_glMultiDrawElements;
PFNGLVERTEXATTRIB3FVPROC xwfgl_glVertexAttrib3fv;
PFNGLGETFLOATVPROC xwfgl_glGetFloatv;
PFNGLTEXSUBIMAGE1DPROC xwfgl_glTexSubImage1D;
PFNGLUNIFORM3IVPROC xwfgl_glUniform3iv;
PFNGLGETTEXIMAGEPROC xwfgl_glGetTexImage;
PFNGLVERTEXATTRIB2FVPROC xwfgl_glVertexAttrib2fv;
PFNGLUSEPROGRAMPROC xwfgl_glUseProgram;
PFNGLVERTEXATTRIB4IVPROC xwfgl_glVertexAttrib4iv;
PFNGLGETTEXLEVELPARAMETERFVPROC xwfgl_glGetTexLevelParameterfv;
PFNGLVERTEXATTRIBI1IPROC xwfgl_glVertexAttribI1i;
PFNGLGENFRAMEBUFFERSPROC xwfgl_glGenFramebuffers;
PFNGLFRAMEBUFFERRENDERBUFFERPROC xwfgl_glFramebufferRenderbuffer;
PFNGLDRAWBUFFERSPROC xwfgl_glDrawBuffers;
PFNGLCLEARBUFFERFVPROC xwfgl_glClearBufferfv;
PFNGLSTENCILFUNCPROC xwfgl_glStencilFunc;
PFNGLGETINTEGERVPROC xwfgl_glGetIntegerv;
PFNGLGETATTACHEDSHADERSPROC xwfgl_glGetAttachedShaders;
PFNGLUNIFORMBLOCKBINDINGPROC xwfgl_glUniformBlockBinding;
PFNGLISRENDERBUFFERPROC xwfgl_glIsRenderbuffer;
PFNGLGETBUFFERPOINTERVPROC xwfgl_glGetBufferPointerv;
PFNGLGETVERTEXATTRIBIIVPROC xwfgl_glGetVertexAttribIiv;
PFNGLDRAWBUFFERPROC xwfgl_glDrawBuffer;
PFNGLFRAMEBUFFERTEXTURE3DPROC xwfgl_glFramebufferTexture3D;
PFNGLUNIFORM1FVPROC xwfgl_glUniform1fv;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC xwfgl_glRenderbufferStorageMultisample;
PFNGLMAPBUFFERRANGEPROC xwfgl_glMapBufferRange;
PFNGLISQUERYPROC xwfgl_glIsQuery;
PFNGLVERTEXATTRIB4NUBVPROC xwfgl_glVertexAttrib4Nubv;
PFNGLUNIFORMMATRIX2FVPROC xwfgl_glUniformMatrix2fv;
PFNGLDISABLEVERTEXATTRIBARRAYPROC xwfgl_glDisableVertexAttribArray;
PFNGLVERTEXATTRIB4SVPROC xwfgl_glVertexAttrib4sv;
PFNGLGETQUERYIVPROC xwfgl_glGetQueryiv;
PFNGLTEXIMAGE2DPROC xwfgl_glTexImage2D;
PFNGLGETPROGRAMINFOLOGPROC xwfgl_glGetProgramInfoLog;
PFNGLSTENCILMASKPROC xwfgl_glStencilMask;
PFNGLUNIFORM4UIPROC xwfgl_glUniform4ui;
PFNGLUNIFORMMATRIX2X4FVPROC xwfgl_glUniformMatrix2x4fv;
PFNGLGETSHADERINFOLOGPROC xwfgl_glGetShaderInfoLog;
PFNGLISTEXTUREPROC xwfgl_glIsTexture;
PFNGLGETUNIFORMINDICESPROC xwfgl_glGetUniformIndices;
PFNGLISSHADERPROC xwfgl_glIsShader;
PFNGLGETSHADERSOURCEPROC xwfgl_glGetShaderSource;
PFNGLVERTEXATTRIBI4UBVPROC xwfgl_glVertexAttribI4ubv;
PFNGLVERTEXATTRIB4BVPROC xwfgl_glVertexAttrib4bv;
PFNGLGETINTEGER64VPROC xwfgl_glGetInteger64v;
PFNGLVERTEXATTRIBPOINTERPROC xwfgl_glVertexAttribPointer;
PFNGLTEXPARAMETERFVPROC xwfgl_glTexParameterfv;
PFNGLGETBUFFERSUBDATAPROC xwfgl_glGetBufferSubData;
PFNGLVERTEXATTRIB1FVPROC xwfgl_glVertexAttrib1fv;
PFNGLTEXPARAMETERIUIVPROC xwfgl_glTexParameterIuiv;
PFNGLENABLEPROC xwfgl_glEnable;
PFNGLGETACTIVEUNIFORMSIVPROC xwfgl_glGetActiveUniformsiv;
PFNGLDRAWARRAYSINSTANCEDPROC xwfgl_glDrawArraysInstanced;
PFNGLVERTEXATTRIBI4IPROC xwfgl_glVertexAttribI4i;
PFNGLSTENCILFUNCSEPARATEPROC xwfgl_glStencilFuncSeparate;
PFNGLDELETEQUERIESPROC xwfgl_glDeleteQueries;
PFNGLPOINTPARAMETERIVPROC xwfgl_glPointParameteriv;
PFNGLBLENDEQUATIONSEPARATEPROC xwfgl_glBlendEquationSeparate;
PFNGLVERTEXATTRIBI1UIPROC xwfgl_glVertexAttribI1ui;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC xwfgl_glCompressedTexSubImage1D;
PFNGLFINISHPROC xwfgl_glFinish;
PFNGLGETATTRIBLOCATIONPROC xwfgl_glGetAttribLocation;
PFNGLVERTEXATTRIB4DVPROC xwfgl_glVertexAttrib4dv;
PFNGLVERTEXATTRIB2SVPROC xwfgl_glVertexAttrib2sv;
PFNGLDELETESHADERPROC xwfgl_glDeleteShader;
PFNGLBLENDFUNCPROC xwfgl_glBlendFunc;
PFNGLCREATEPROGRAMPROC xwfgl_glCreateProgram;
PFNGLTEXIMAGE3DPROC xwfgl_glTexImage3D;
PFNGLVERTEXATTRIB4NSVPROC xwfgl_glVertexAttrib4Nsv;
PFNGLISFRAMEBUFFERPROC xwfgl_glIsFramebuffer;
PFNGLVERTEXATTRIBI4UIPROC xwfgl_glVertexAttribI4ui;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC xwfgl_glFlushMappedBufferRange;
PFNGLVIEWPORTPROC xwfgl_glViewport;
PFNGLVERTEXATTRIBI1UIVPROC xwfgl_glVertexAttribI1uiv;
PFNGLVERTEXATTRIB2DPROC xwfgl_glVertexAttrib2d;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC xwfgl_glTransformFeedbackVaryings;
PFNGLVERTEXATTRIB2FPROC xwfgl_glVertexAttrib2f;
PFNGLGETVERTEXATTRIBDVPROC xwfgl_glGetVertexAttribdv;
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC xwfgl_glMultiDrawElementsBaseVertex;
PFNGLPRIMITIVERESTARTINDEXPROC xwfgl_glPrimitiveRestartIndex;
PFNGLUNIFORM2UIPROC xwfgl_glUniform2ui;
PFNGLPOLYGONOFFSETPROC xwfgl_glPolygonOffset;
PFNGLGETUNIFORMUIVPROC xwfgl_glGetUniformuiv;
PFNGLVERTEXATTRIBI3IPROC xwfgl_glVertexAttribI3i;
PFNGLVERTEXATTRIB2SPROC xwfgl_glVertexAttrib2s;
PFNGLTEXIMAGE3DMULTISAMPLEPROC xwfgl_glTexImage3DMultisample;
PFNGLUNIFORMMATRIX4FVPROC xwfgl_glUniformMatrix4fv;
PFNGLDEPTHRANGEPROC xwfgl_glDepthRange;
PFNGLGETACTIVEUNIFORMPROC xwfgl_glGetActiveUniform;
PFNGLVERTEXATTRIBI4USVPROC xwfgl_glVertexAttribI4usv;
PFNGLTEXPARAMETERFPROC xwfgl_glTexParameterf;
PFNGLCLEARBUFFERFIPROC xwfgl_glClearBufferfi;
PFNGLTEXPARAMETERIPROC xwfgl_glTexParameteri;
PFNGLFRONTFACEPROC xwfgl_glFrontFace;
PFNGLDELETEBUFFERSPROC xwfgl_glDeleteBuffers;
PFNGLSCISSORPROC xwfgl_glScissor;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC xwfgl_glDrawElementsInstancedBaseVertex;
PFNGLGETBOOLEANVPROC xwfgl_glGetBooleanv;
PFNGLTEXBUFFERPROC xwfgl_glTexBuffer;
PFNGLPIXELSTOREIPROC xwfgl_glPixelStorei;
PFNGLVALIDATEPROGRAMPROC xwfgl_glValidateProgram;
PFNGLPIXELSTOREFPROC xwfgl_glPixelStoref;
PFNGLCLEARBUFFERUIVPROC xwfgl_glClearBufferuiv;
PFNGLUNIFORM3UIVPROC xwfgl_glUniform3uiv;
PFNGLGETBOOLEANI_VPROC xwfgl_glGetBooleani_v;
PFNGLVERTEXATTRIBIPOINTERPROC xwfgl_glVertexAttribIPointer;
static void load_GL_VERSION_1_0(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_1_0) return;
	xwfgl_glCullFace = (PFNGLCULLFACEPROC)load("glCullFace");
	xwfgl_glFrontFace = (PFNGLFRONTFACEPROC)load("glFrontFace");
	xwfgl_glHint = (PFNGLHINTPROC)load("glHint");
	xwfgl_glLineWidth = (PFNGLLINEWIDTHPROC)load("glLineWidth");
	xwfgl_glPointSize = (PFNGLPOINTSIZEPROC)load("glPointSize");
	xwfgl_glPolygonMode = (PFNGLPOLYGONMODEPROC)load("glPolygonMode");
	xwfgl_glScissor = (PFNGLSCISSORPROC)load("glScissor");
	xwfgl_glTexParameterf = (PFNGLTEXPARAMETERFPROC)load("glTexParameterf");
	xwfgl_glTexParameterfv = (PFNGLTEXPARAMETERFVPROC)load("glTexParameterfv");
	xwfgl_glTexParameteri = (PFNGLTEXPARAMETERIPROC)load("glTexParameteri");
	xwfgl_glTexParameteriv = (PFNGLTEXPARAMETERIVPROC)load("glTexParameteriv");
	xwfgl_glTexImage1D = (PFNGLTEXIMAGE1DPROC)load("glTexImage1D");
	xwfgl_glTexImage2D = (PFNGLTEXIMAGE2DPROC)load("glTexImage2D");
	xwfgl_glDrawBuffer = (PFNGLDRAWBUFFERPROC)load("glDrawBuffer");
	xwfgl_glClear = (PFNGLCLEARPROC)load("glClear");
	xwfgl_glClearColor = (PFNGLCLEARCOLORPROC)load("glClearColor");
	xwfgl_glClearStencil = (PFNGLCLEARSTENCILPROC)load("glClearStencil");
	xwfgl_glClearDepth = (PFNGLCLEARDEPTHPROC)load("glClearDepth");
	xwfgl_glStencilMask = (PFNGLSTENCILMASKPROC)load("glStencilMask");
	xwfgl_glColorMask = (PFNGLCOLORMASKPROC)load("glColorMask");
	xwfgl_glDepthMask = (PFNGLDEPTHMASKPROC)load("glDepthMask");
	xwfgl_glDisable = (PFNGLDISABLEPROC)load("glDisable");
	xwfgl_glEnable = (PFNGLENABLEPROC)load("glEnable");
	xwfgl_glFinish = (PFNGLFINISHPROC)load("glFinish");
	xwfgl_glFlush = (PFNGLFLUSHPROC)load("glFlush");
	xwfgl_glBlendFunc = (PFNGLBLENDFUNCPROC)load("glBlendFunc");
	xwfgl_glLogicOp = (PFNGLLOGICOPPROC)load("glLogicOp");
	xwfgl_glStencilFunc = (PFNGLSTENCILFUNCPROC)load("glStencilFunc");
	xwfgl_glStencilOp = (PFNGLSTENCILOPPROC)load("glStencilOp");
	xwfgl_glDepthFunc = (PFNGLDEPTHFUNCPROC)load("glDepthFunc");
	xwfgl_glPixelStoref = (PFNGLPIXELSTOREFPROC)load("glPixelStoref");
	xwfgl_glPixelStorei = (PFNGLPIXELSTOREIPROC)load("glPixelStorei");
	xwfgl_glReadBuffer = (PFNGLREADBUFFERPROC)load("glReadBuffer");
	xwfgl_glReadPixels = (PFNGLREADPIXELSPROC)load("glReadPixels");
	xwfgl_glGetBooleanv = (PFNGLGETBOOLEANVPROC)load("glGetBooleanv");
	xwfgl_glGetDoublev = (PFNGLGETDOUBLEVPROC)load("glGetDoublev");
	xwfgl_glGetError = (PFNGLGETERRORPROC)load("glGetError");
	xwfgl_glGetFloatv = (PFNGLGETFLOATVPROC)load("glGetFloatv");
	xwfgl_glGetIntegerv = (PFNGLGETINTEGERVPROC)load("glGetIntegerv");
	xwfgl_glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
	xwfgl_glGetTexImage = (PFNGLGETTEXIMAGEPROC)load("glGetTexImage");
	xwfgl_glGetTexParameterfv = (PFNGLGETTEXPARAMETERFVPROC)load("glGetTexParameterfv");
	xwfgl_glGetTexParameteriv = (PFNGLGETTEXPARAMETERIVPROC)load("glGetTexParameteriv");
	xwfgl_glGetTexLevelParameterfv = (PFNGLGETTEXLEVELPARAMETERFVPROC)load("glGetTexLevelParameterfv");
	xwfgl_glGetTexLevelParameteriv = (PFNGLGETTEXLEVELPARAMETERIVPROC)load("glGetTexLevelParameteriv");
	xwfgl_glIsEnabled = (PFNGLISENABLEDPROC)load("glIsEnabled");
	xwfgl_glDepthRange = (PFNGLDEPTHRANGEPROC)load("glDepthRange");
	xwfgl_glViewport = (PFNGLVIEWPORTPROC)load("glViewport");
}
static void load_GL_VERSION_1_1(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_1_1) return;
	xwfgl_glDrawArrays = (PFNGLDRAWARRAYSPROC)load("glDrawArrays");
	xwfgl_glDrawElements = (PFNGLDRAWELEMENTSPROC)load("glDrawElements");
	xwfgl_glPolygonOffset = (PFNGLPOLYGONOFFSETPROC)load("glPolygonOffset");
	xwfgl_glCopyTexImage1D = (PFNGLCOPYTEXIMAGE1DPROC)load("glCopyTexImage1D");
	xwfgl_glCopyTexImage2D = (PFNGLCOPYTEXIMAGE2DPROC)load("glCopyTexImage2D");
	xwfgl_glCopyTexSubImage1D = (PFNGLCOPYTEXSUBIMAGE1DPROC)load("glCopyTexSubImage1D");
	xwfgl_glCopyTexSubImage2D = (PFNGLCOPYTEXSUBIMAGE2DPROC)load("glCopyTexSubImage2D");
	xwfgl_glTexSubImage1D = (PFNGLTEXSUBIMAGE1DPROC)load("glTexSubImage1D");
	xwfgl_glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC)load("glTexSubImage2D");
	xwfgl_glBindTexture = (PFNGLBINDTEXTUREPROC)load("glBindTexture");
	xwfgl_glDeleteTextures = (PFNGLDELETETEXTURESPROC)load("glDeleteTextures");
	xwfgl_glGenTextures = (PFNGLGENTEXTURESPROC)load("glGenTextures");
	xwfgl_glIsTexture = (PFNGLISTEXTUREPROC)load("glIsTexture");
}
static void load_GL_VERSION_1_2(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_1_2) return;
	xwfgl_glDrawRangeElements = (PFNGLDRAWRANGEELEMENTSPROC)load("glDrawRangeElements");
	xwfgl_glTexImage3D = (PFNGLTEXIMAGE3DPROC)load("glTexImage3D");
	xwfgl_glTexSubImage3D = (PFNGLTEXSUBIMAGE3DPROC)load("glTexSubImage3D");
	xwfgl_glCopyTexSubImage3D = (PFNGLCOPYTEXSUBIMAGE3DPROC)load("glCopyTexSubImage3D");
}
static void load_GL_VERSION_1_3(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_1_3) return;
	xwfgl_glActiveTexture = (PFNGLACTIVETEXTUREPROC)load("glActiveTexture");
	xwfgl_glSampleCoverage = (PFNGLSAMPLECOVERAGEPROC)load("glSampleCoverage");
	xwfgl_glCompressedTexImage3D = (PFNGLCOMPRESSEDTEXIMAGE3DPROC)load("glCompressedTexImage3D");
	xwfgl_glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC)load("glCompressedTexImage2D");
	xwfgl_glCompressedTexImage1D = (PFNGLCOMPRESSEDTEXIMAGE1DPROC)load("glCompressedTexImage1D");
	xwfgl_glCompressedTexSubImage3D = (PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC)load("glCompressedTexSubImage3D");
	xwfgl_glCompressedTexSubImage2D = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC)load("glCompressedTexSubImage2D");
	xwfgl_glCompressedTexSubImage1D = (PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC)load("glCompressedTexSubImage1D");
	xwfgl_glGetCompressedTexImage = (PFNGLGETCOMPRESSEDTEXIMAGEPROC)load("glGetCompressedTexImage");
}
static void load_GL_VERSION_1_4(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_1_4) return;
	xwfgl_glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC)load("glBlendFuncSeparate");
	xwfgl_glMultiDrawArrays = (PFNGLMULTIDRAWARRAYSPROC)load("glMultiDrawArrays");
	xwfgl_glMultiDrawElements = (PFNGLMULTIDRAWELEMENTSPROC)load("glMultiDrawElements");
	xwfgl_glPointParameterf = (PFNGLPOINTPARAMETERFPROC)load("glPointParameterf");
	xwfgl_glPointParameterfv = (PFNGLPOINTPARAMETERFVPROC)load("glPointParameterfv");
	xwfgl_glPointParameteri = (PFNGLPOINTPARAMETERIPROC)load("glPointParameteri");
	xwfgl_glPointParameteriv = (PFNGLPOINTPARAMETERIVPROC)load("glPointParameteriv");
	xwfgl_glBlendColor = (PFNGLBLENDCOLORPROC)load("glBlendColor");
	xwfgl_glBlendEquation = (PFNGLBLENDEQUATIONPROC)load("glBlendEquation");
}
static void load_GL_VERSION_1_5(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_1_5) return;
	xwfgl_glGenQueries = (PFNGLGENQUERIESPROC)load("glGenQueries");
	xwfgl_glDeleteQueries = (PFNGLDELETEQUERIESPROC)load("glDeleteQueries");
	xwfgl_glIsQuery = (PFNGLISQUERYPROC)load("glIsQuery");
	xwfgl_glBeginQuery = (PFNGLBEGINQUERYPROC)load("glBeginQuery");
	xwfgl_glEndQuery = (PFNGLENDQUERYPROC)load("glEndQuery");
	xwfgl_glGetQueryiv = (PFNGLGETQUERYIVPROC)load("glGetQueryiv");
	xwfgl_glGetQueryObjectiv = (PFNGLGETQUERYOBJECTIVPROC)load("glGetQueryObjectiv");
	xwfgl_glGetQueryObjectuiv = (PFNGLGETQUERYOBJECTUIVPROC)load("glGetQueryObjectuiv");
	xwfgl_glBindBuffer = (PFNGLBINDBUFFERPROC)load("glBindBuffer");
	xwfgl_glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)load("glDeleteBuffers");
	xwfgl_glGenBuffers = (PFNGLGENBUFFERSPROC)load("glGenBuffers");
	xwfgl_glIsBuffer = (PFNGLISBUFFERPROC)load("glIsBuffer");
	xwfgl_glBufferData = (PFNGLBUFFERDATAPROC)load("glBufferData");
	xwfgl_glBufferSubData = (PFNGLBUFFERSUBDATAPROC)load("glBufferSubData");
	xwfgl_glGetBufferSubData = (PFNGLGETBUFFERSUBDATAPROC)load("glGetBufferSubData");
	xwfgl_glMapBuffer = (PFNGLMAPBUFFERPROC)load("glMapBuffer");
	xwfgl_glUnmapBuffer = (PFNGLUNMAPBUFFERPROC)load("glUnmapBuffer");
	xwfgl_glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC)load("glGetBufferParameteriv");
	xwfgl_glGetBufferPointerv = (PFNGLGETBUFFERPOINTERVPROC)load("glGetBufferPointerv");
}
static void load_GL_VERSION_2_0(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_2_0) return;
	xwfgl_glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC)load("glBlendEquationSeparate");
	xwfgl_glDrawBuffers = (PFNGLDRAWBUFFERSPROC)load("glDrawBuffers");
	xwfgl_glStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC)load("glStencilOpSeparate");
	xwfgl_glStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC)load("glStencilFuncSeparate");
	xwfgl_glStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC)load("glStencilMaskSeparate");
	xwfgl_glAttachShader = (PFNGLATTACHSHADERPROC)load("glAttachShader");
	xwfgl_glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC)load("glBindAttribLocation");
	xwfgl_glCompileShader = (PFNGLCOMPILESHADERPROC)load("glCompileShader");
	xwfgl_glCreateProgram = (PFNGLCREATEPROGRAMPROC)load("glCreateProgram");
	xwfgl_glCreateShader = (PFNGLCREATESHADERPROC)load("glCreateShader");
	xwfgl_glDeleteProgram = (PFNGLDELETEPROGRAMPROC)load("glDeleteProgram");
	xwfgl_glDeleteShader = (PFNGLDELETESHADERPROC)load("glDeleteShader");
	xwfgl_glDetachShader = (PFNGLDETACHSHADERPROC)load("glDetachShader");
	xwfgl_glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)load("glDisableVertexAttribArray");
	xwfgl_glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)load("glEnableVertexAttribArray");
	xwfgl_glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC)load("glGetActiveAttrib");
	xwfgl_glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC)load("glGetActiveUniform");
	xwfgl_glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC)load("glGetAttachedShaders");
	xwfgl_glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)load("glGetAttribLocation");
	xwfgl_glGetProgramiv = (PFNGLGETPROGRAMIVPROC)load("glGetProgramiv");
	xwfgl_glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)load("glGetProgramInfoLog");
	xwfgl_glGetShaderiv = (PFNGLGETSHADERIVPROC)load("glGetShaderiv");
	xwfgl_glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)load("glGetShaderInfoLog");
	xwfgl_glGetShaderSource = (PFNGLGETSHADERSOURCEPROC)load("glGetShaderSource");
	xwfgl_glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)load("glGetUniformLocation");
	xwfgl_glGetUniformfv = (PFNGLGETUNIFORMFVPROC)load("glGetUniformfv");
	xwfgl_glGetUniformiv = (PFNGLGETUNIFORMIVPROC)load("glGetUniformiv");
	xwfgl_glGetVertexAttribdv = (PFNGLGETVERTEXATTRIBDVPROC)load("glGetVertexAttribdv");
	xwfgl_glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC)load("glGetVertexAttribfv");
	xwfgl_glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC)load("glGetVertexAttribiv");
	xwfgl_glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC)load("glGetVertexAttribPointerv");
	xwfgl_glIsProgram = (PFNGLISPROGRAMPROC)load("glIsProgram");
	xwfgl_glIsShader = (PFNGLISSHADERPROC)load("glIsShader");
	xwfgl_glLinkProgram = (PFNGLLINKPROGRAMPROC)load("glLinkProgram");
	xwfgl_glShaderSource = (PFNGLSHADERSOURCEPROC)load("glShaderSource");
	xwfgl_glUseProgram = (PFNGLUSEPROGRAMPROC)load("glUseProgram");
	xwfgl_glUniform1f = (PFNGLUNIFORM1FPROC)load("glUniform1f");
	xwfgl_glUniform2f = (PFNGLUNIFORM2FPROC)load("glUniform2f");
	xwfgl_glUniform3f = (PFNGLUNIFORM3FPROC)load("glUniform3f");
	xwfgl_glUniform4f = (PFNGLUNIFORM4FPROC)load("glUniform4f");
	xwfgl_glUniform1i = (PFNGLUNIFORM1IPROC)load("glUniform1i");
	xwfgl_glUniform2i = (PFNGLUNIFORM2IPROC)load("glUniform2i");
	xwfgl_glUniform3i = (PFNGLUNIFORM3IPROC)load("glUniform3i");
	xwfgl_glUniform4i = (PFNGLUNIFORM4IPROC)load("glUniform4i");
	xwfgl_glUniform1fv = (PFNGLUNIFORM1FVPROC)load("glUniform1fv");
	xwfgl_glUniform2fv = (PFNGLUNIFORM2FVPROC)load("glUniform2fv");
	xwfgl_glUniform3fv = (PFNGLUNIFORM3FVPROC)load("glUniform3fv");
	xwfgl_glUniform4fv = (PFNGLUNIFORM4FVPROC)load("glUniform4fv");
	xwfgl_glUniform1iv = (PFNGLUNIFORM1IVPROC)load("glUniform1iv");
	xwfgl_glUniform2iv = (PFNGLUNIFORM2IVPROC)load("glUniform2iv");
	xwfgl_glUniform3iv = (PFNGLUNIFORM3IVPROC)load("glUniform3iv");
	xwfgl_glUniform4iv = (PFNGLUNIFORM4IVPROC)load("glUniform4iv");
	xwfgl_glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)load("glUniformMatrix2fv");
	xwfgl_glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)load("glUniformMatrix3fv");
	xwfgl_glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)load("glUniformMatrix4fv");
	xwfgl_glValidateProgram = (PFNGLVALIDATEPROGRAMPROC)load("glValidateProgram");
	xwfgl_glVertexAttrib1d = (PFNGLVERTEXATTRIB1DPROC)load("glVertexAttrib1d");
	xwfgl_glVertexAttrib1dv = (PFNGLVERTEXATTRIB1DVPROC)load("glVertexAttrib1dv");
	xwfgl_glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC)load("glVertexAttrib1f");
	xwfgl_glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC)load("glVertexAttrib1fv");
	xwfgl_glVertexAttrib1s = (PFNGLVERTEXATTRIB1SPROC)load("glVertexAttrib1s");
	xwfgl_glVertexAttrib1sv = (PFNGLVERTEXATTRIB1SVPROC)load("glVertexAttrib1sv");
	xwfgl_glVertexAttrib2d = (PFNGLVERTEXATTRIB2DPROC)load("glVertexAttrib2d");
	xwfgl_glVertexAttrib2dv = (PFNGLVERTEXATTRIB2DVPROC)load("glVertexAttrib2dv");
	xwfgl_glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC)load("glVertexAttrib2f");
	xwfgl_glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC)load("glVertexAttrib2fv");
	xwfgl_glVertexAttrib2s = (PFNGLVERTEXATTRIB2SPROC)load("glVertexAttrib2s");
	xwfgl_glVertexAttrib2sv = (PFNGLVERTEXATTRIB2SVPROC)load("glVertexAttrib2sv");
	xwfgl_glVertexAttrib3d = (PFNGLVERTEXATTRIB3DPROC)load("glVertexAttrib3d");
	xwfgl_glVertexAttrib3dv = (PFNGLVERTEXATTRIB3DVPROC)load("glVertexAttrib3dv");
	xwfgl_glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC)load("glVertexAttrib3f");
	xwfgl_glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC)load("glVertexAttrib3fv");
	xwfgl_glVertexAttrib3s = (PFNGLVERTEXATTRIB3SPROC)load("glVertexAttrib3s");
	xwfgl_glVertexAttrib3sv = (PFNGLVERTEXATTRIB3SVPROC)load("glVertexAttrib3sv");
	xwfgl_glVertexAttrib4Nbv = (PFNGLVERTEXATTRIB4NBVPROC)load("glVertexAttrib4Nbv");
	xwfgl_glVertexAttrib4Niv = (PFNGLVERTEXATTRIB4NIVPROC)load("glVertexAttrib4Niv");
	xwfgl_glVertexAttrib4Nsv = (PFNGLVERTEXATTRIB4NSVPROC)load("glVertexAttrib4Nsv");
	xwfgl_glVertexAttrib4Nub = (PFNGLVERTEXATTRIB4NUBPROC)load("glVertexAttrib4Nub");
	xwfgl_glVertexAttrib4Nubv = (PFNGLVERTEXATTRIB4NUBVPROC)load("glVertexAttrib4Nubv");
	xwfgl_glVertexAttrib4Nuiv = (PFNGLVERTEXATTRIB4NUIVPROC)load("glVertexAttrib4Nuiv");
	xwfgl_glVertexAttrib4Nusv = (PFNGLVERTEXATTRIB4NUSVPROC)load("glVertexAttrib4Nusv");
	xwfgl_glVertexAttrib4bv = (PFNGLVERTEXATTRIB4BVPROC)load("glVertexAttrib4bv");
	xwfgl_glVertexAttrib4d = (PFNGLVERTEXATTRIB4DPROC)load("glVertexAttrib4d");
	xwfgl_glVertexAttrib4dv = (PFNGLVERTEXATTRIB4DVPROC)load("glVertexAttrib4dv");
	xwfgl_glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC)load("glVertexAttrib4f");
	xwfgl_glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC)load("glVertexAttrib4fv");
	xwfgl_glVertexAttrib4iv = (PFNGLVERTEXATTRIB4IVPROC)load("glVertexAttrib4iv");
	xwfgl_glVertexAttrib4s = (PFNGLVERTEXATTRIB4SPROC)load("glVertexAttrib4s");
	xwfgl_glVertexAttrib4sv = (PFNGLVERTEXATTRIB4SVPROC)load("glVertexAttrib4sv");
	xwfgl_glVertexAttrib4ubv = (PFNGLVERTEXATTRIB4UBVPROC)load("glVertexAttrib4ubv");
	xwfgl_glVertexAttrib4uiv = (PFNGLVERTEXATTRIB4UIVPROC)load("glVertexAttrib4uiv");
	xwfgl_glVertexAttrib4usv = (PFNGLVERTEXATTRIB4USVPROC)load("glVertexAttrib4usv");
	xwfgl_glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)load("glVertexAttribPointer");
}
static void load_GL_VERSION_2_1(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_2_1) return;
	xwfgl_glUniformMatrix2x3fv = (PFNGLUNIFORMMATRIX2X3FVPROC)load("glUniformMatrix2x3fv");
	xwfgl_glUniformMatrix3x2fv = (PFNGLUNIFORMMATRIX3X2FVPROC)load("glUniformMatrix3x2fv");
	xwfgl_glUniformMatrix2x4fv = (PFNGLUNIFORMMATRIX2X4FVPROC)load("glUniformMatrix2x4fv");
	xwfgl_glUniformMatrix4x2fv = (PFNGLUNIFORMMATRIX4X2FVPROC)load("glUniformMatrix4x2fv");
	xwfgl_glUniformMatrix3x4fv = (PFNGLUNIFORMMATRIX3X4FVPROC)load("glUniformMatrix3x4fv");
	xwfgl_glUniformMatrix4x3fv = (PFNGLUNIFORMMATRIX4X3FVPROC)load("glUniformMatrix4x3fv");
}
static void load_GL_VERSION_3_0(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_3_0) return;
	xwfgl_glColorMaski = (PFNGLCOLORMASKIPROC)load("glColorMaski");
	xwfgl_glGetBooleani_v = (PFNGLGETBOOLEANI_VPROC)load("glGetBooleani_v");
	xwfgl_glGetIntegeri_v = (PFNGLGETINTEGERI_VPROC)load("glGetIntegeri_v");
	xwfgl_glEnablei = (PFNGLENABLEIPROC)load("glEnablei");
	xwfgl_glDisablei = (PFNGLDISABLEIPROC)load("glDisablei");
	xwfgl_glIsEnabledi = (PFNGLISENABLEDIPROC)load("glIsEnabledi");
	xwfgl_glBeginTransformFeedback = (PFNGLBEGINTRANSFORMFEEDBACKPROC)load("glBeginTransformFeedback");
	xwfgl_glEndTransformFeedback = (PFNGLENDTRANSFORMFEEDBACKPROC)load("glEndTransformFeedback");
	xwfgl_glBindBufferRange = (PFNGLBINDBUFFERRANGEPROC)load("glBindBufferRange");
	xwfgl_glBindBufferBase = (PFNGLBINDBUFFERBASEPROC)load("glBindBufferBase");
	xwfgl_glTransformFeedbackVaryings = (PFNGLTRANSFORMFEEDBACKVARYINGSPROC)load("glTransformFeedbackVaryings");
	xwfgl_glGetTransformFeedbackVarying = (PFNGLGETTRANSFORMFEEDBACKVARYINGPROC)load("glGetTransformFeedbackVarying");
	xwfgl_glClampColor = (PFNGLCLAMPCOLORPROC)load("glClampColor");
	xwfgl_glBeginConditionalRender = (PFNGLBEGINCONDITIONALRENDERPROC)load("glBeginConditionalRender");
	xwfgl_glEndConditionalRender = (PFNGLENDCONDITIONALRENDERPROC)load("glEndConditionalRender");
	xwfgl_glVertexAttribIPointer = (PFNGLVERTEXATTRIBIPOINTERPROC)load("glVertexAttribIPointer");
	xwfgl_glGetVertexAttribIiv = (PFNGLGETVERTEXATTRIBIIVPROC)load("glGetVertexAttribIiv");
	xwfgl_glGetVertexAttribIuiv = (PFNGLGETVERTEXATTRIBIUIVPROC)load("glGetVertexAttribIuiv");
	xwfgl_glVertexAttribI1i = (PFNGLVERTEXATTRIBI1IPROC)load("glVertexAttribI1i");
	xwfgl_glVertexAttribI2i = (PFNGLVERTEXATTRIBI2IPROC)load("glVertexAttribI2i");
	xwfgl_glVertexAttribI3i = (PFNGLVERTEXATTRIBI3IPROC)load("glVertexAttribI3i");
	xwfgl_glVertexAttribI4i = (PFNGLVERTEXATTRIBI4IPROC)load("glVertexAttribI4i");
	xwfgl_glVertexAttribI1ui = (PFNGLVERTEXATTRIBI1UIPROC)load("glVertexAttribI1ui");
	xwfgl_glVertexAttribI2ui = (PFNGLVERTEXATTRIBI2UIPROC)load("glVertexAttribI2ui");
	xwfgl_glVertexAttribI3ui = (PFNGLVERTEXATTRIBI3UIPROC)load("glVertexAttribI3ui");
	xwfgl_glVertexAttribI4ui = (PFNGLVERTEXATTRIBI4UIPROC)load("glVertexAttribI4ui");
	xwfgl_glVertexAttribI1iv = (PFNGLVERTEXATTRIBI1IVPROC)load("glVertexAttribI1iv");
	xwfgl_glVertexAttribI2iv = (PFNGLVERTEXATTRIBI2IVPROC)load("glVertexAttribI2iv");
	xwfgl_glVertexAttribI3iv = (PFNGLVERTEXATTRIBI3IVPROC)load("glVertexAttribI3iv");
	xwfgl_glVertexAttribI4iv = (PFNGLVERTEXATTRIBI4IVPROC)load("glVertexAttribI4iv");
	xwfgl_glVertexAttribI1uiv = (PFNGLVERTEXATTRIBI1UIVPROC)load("glVertexAttribI1uiv");
	xwfgl_glVertexAttribI2uiv = (PFNGLVERTEXATTRIBI2UIVPROC)load("glVertexAttribI2uiv");
	xwfgl_glVertexAttribI3uiv = (PFNGLVERTEXATTRIBI3UIVPROC)load("glVertexAttribI3uiv");
	xwfgl_glVertexAttribI4uiv = (PFNGLVERTEXATTRIBI4UIVPROC)load("glVertexAttribI4uiv");
	xwfgl_glVertexAttribI4bv = (PFNGLVERTEXATTRIBI4BVPROC)load("glVertexAttribI4bv");
	xwfgl_glVertexAttribI4sv = (PFNGLVERTEXATTRIBI4SVPROC)load("glVertexAttribI4sv");
	xwfgl_glVertexAttribI4ubv = (PFNGLVERTEXATTRIBI4UBVPROC)load("glVertexAttribI4ubv");
	xwfgl_glVertexAttribI4usv = (PFNGLVERTEXATTRIBI4USVPROC)load("glVertexAttribI4usv");
	xwfgl_glGetUniformuiv = (PFNGLGETUNIFORMUIVPROC)load("glGetUniformuiv");
	xwfgl_glBindFragDataLocation = (PFNGLBINDFRAGDATALOCATIONPROC)load("glBindFragDataLocation");
	xwfgl_glGetFragDataLocation = (PFNGLGETFRAGDATALOCATIONPROC)load("glGetFragDataLocation");
	xwfgl_glUniform1ui = (PFNGLUNIFORM1UIPROC)load("glUniform1ui");
	xwfgl_glUniform2ui = (PFNGLUNIFORM2UIPROC)load("glUniform2ui");
	xwfgl_glUniform3ui = (PFNGLUNIFORM3UIPROC)load("glUniform3ui");
	xwfgl_glUniform4ui = (PFNGLUNIFORM4UIPROC)load("glUniform4ui");
	xwfgl_glUniform1uiv = (PFNGLUNIFORM1UIVPROC)load("glUniform1uiv");
	xwfgl_glUniform2uiv = (PFNGLUNIFORM2UIVPROC)load("glUniform2uiv");
	xwfgl_glUniform3uiv = (PFNGLUNIFORM3UIVPROC)load("glUniform3uiv");
	xwfgl_glUniform4uiv = (PFNGLUNIFORM4UIVPROC)load("glUniform4uiv");
	xwfgl_glTexParameterIiv = (PFNGLTEXPARAMETERIIVPROC)load("glTexParameterIiv");
	xwfgl_glTexParameterIuiv = (PFNGLTEXPARAMETERIUIVPROC)load("glTexParameterIuiv");
	xwfgl_glGetTexParameterIiv = (PFNGLGETTEXPARAMETERIIVPROC)load("glGetTexParameterIiv");
	xwfgl_glGetTexParameterIuiv = (PFNGLGETTEXPARAMETERIUIVPROC)load("glGetTexParameterIuiv");
	xwfgl_glClearBufferiv = (PFNGLCLEARBUFFERIVPROC)load("glClearBufferiv");
	xwfgl_glClearBufferuiv = (PFNGLCLEARBUFFERUIVPROC)load("glClearBufferuiv");
	xwfgl_glClearBufferfv = (PFNGLCLEARBUFFERFVPROC)load("glClearBufferfv");
	xwfgl_glClearBufferfi = (PFNGLCLEARBUFFERFIPROC)load("glClearBufferfi");
	xwfgl_glGetStringi = (PFNGLGETSTRINGIPROC)load("glGetStringi");
	xwfgl_glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC)load("glIsRenderbuffer");
	xwfgl_glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)load("glBindRenderbuffer");
	xwfgl_glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)load("glDeleteRenderbuffers");
	xwfgl_glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)load("glGenRenderbuffers");
	xwfgl_glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)load("glRenderbufferStorage");
	xwfgl_glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)load("glGetRenderbufferParameteriv");
	xwfgl_glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC)load("glIsFramebuffer");
	xwfgl_glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)load("glBindFramebuffer");
	xwfgl_glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)load("glDeleteFramebuffers");
	xwfgl_glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC)load("glGenFramebuffers");
	xwfgl_glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)load("glCheckFramebufferStatus");
	xwfgl_glFramebufferTexture1D = (PFNGLFRAMEBUFFERTEXTURE1DPROC)load("glFramebufferTexture1D");
	xwfgl_glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)load("glFramebufferTexture2D");
	xwfgl_glFramebufferTexture3D = (PFNGLFRAMEBUFFERTEXTURE3DPROC)load("glFramebufferTexture3D");
	xwfgl_glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)load("glFramebufferRenderbuffer");
	xwfgl_glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)load("glGetFramebufferAttachmentParameteriv");
	xwfgl_glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)load("glGenerateMipmap");
	xwfgl_glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC)load("glBlitFramebuffer");
	xwfgl_glRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC)load("glRenderbufferStorageMultisample");
	xwfgl_glFramebufferTextureLayer = (PFNGLFRAMEBUFFERTEXTURELAYERPROC)load("glFramebufferTextureLayer");
	xwfgl_glMapBufferRange = (PFNGLMAPBUFFERRANGEPROC)load("glMapBufferRange");
	xwfgl_glFlushMappedBufferRange = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC)load("glFlushMappedBufferRange");
	xwfgl_glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)load("glBindVertexArray");
	xwfgl_glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)load("glDeleteVertexArrays");
	xwfgl_glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)load("glGenVertexArrays");
	xwfgl_glIsVertexArray = (PFNGLISVERTEXARRAYPROC)load("glIsVertexArray");
}
static void load_GL_VERSION_3_1(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_3_1) return;
	xwfgl_glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC)load("glDrawArraysInstanced");
	xwfgl_glDrawElementsInstanced = (PFNGLDRAWELEMENTSINSTANCEDPROC)load("glDrawElementsInstanced");
	xwfgl_glTexBuffer = (PFNGLTEXBUFFERPROC)load("glTexBuffer");
	xwfgl_glPrimitiveRestartIndex = (PFNGLPRIMITIVERESTARTINDEXPROC)load("glPrimitiveRestartIndex");
	xwfgl_glCopyBufferSubData = (PFNGLCOPYBUFFERSUBDATAPROC)load("glCopyBufferSubData");
	xwfgl_glGetUniformIndices = (PFNGLGETUNIFORMINDICESPROC)load("glGetUniformIndices");
	xwfgl_glGetActiveUniformsiv = (PFNGLGETACTIVEUNIFORMSIVPROC)load("glGetActiveUniformsiv");
	xwfgl_glGetActiveUniformName = (PFNGLGETACTIVEUNIFORMNAMEPROC)load("glGetActiveUniformName");
	xwfgl_glGetUniformBlockIndex = (PFNGLGETUNIFORMBLOCKINDEXPROC)load("glGetUniformBlockIndex");
	xwfgl_glGetActiveUniformBlockiv = (PFNGLGETACTIVEUNIFORMBLOCKIVPROC)load("glGetActiveUniformBlockiv");
	xwfgl_glGetActiveUniformBlockName = (PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC)load("glGetActiveUniformBlockName");
	xwfgl_glUniformBlockBinding = (PFNGLUNIFORMBLOCKBINDINGPROC)load("glUniformBlockBinding");
	xwfgl_glBindBufferRange = (PFNGLBINDBUFFERRANGEPROC)load("glBindBufferRange");
	xwfgl_glBindBufferBase = (PFNGLBINDBUFFERBASEPROC)load("glBindBufferBase");
	xwfgl_glGetIntegeri_v = (PFNGLGETINTEGERI_VPROC)load("glGetIntegeri_v");
}
static void load_GL_VERSION_3_2(XWFGLloadproc load) {
	if(!XWFGL_GL_VERSION_3_2) return;
	xwfgl_glDrawElementsBaseVertex = (PFNGLDRAWELEMENTSBASEVERTEXPROC)load("glDrawElementsBaseVertex");
	xwfgl_glDrawRangeElementsBaseVertex = (PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC)load("glDrawRangeElementsBaseVertex");
	xwfgl_glDrawElementsInstancedBaseVertex = (PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC)load("glDrawElementsInstancedBaseVertex");
	xwfgl_glMultiDrawElementsBaseVertex = (PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC)load("glMultiDrawElementsBaseVertex");
	xwfgl_glProvokingVertex = (PFNGLPROVOKINGVERTEXPROC)load("glProvokingVertex");
	xwfgl_glFenceSync = (PFNGLFENCESYNCPROC)load("glFenceSync");
	xwfgl_glIsSync = (PFNGLISSYNCPROC)load("glIsSync");
	xwfgl_glDeleteSync = (PFNGLDELETESYNCPROC)load("glDeleteSync");
	xwfgl_glClientWaitSync = (PFNGLCLIENTWAITSYNCPROC)load("glClientWaitSync");
	xwfgl_glWaitSync = (PFNGLWAITSYNCPROC)load("glWaitSync");
	xwfgl_glGetInteger64v = (PFNGLGETINTEGER64VPROC)load("glGetInteger64v");
	xwfgl_glGetSynciv = (PFNGLGETSYNCIVPROC)load("glGetSynciv");
	xwfgl_glGetInteger64i_v = (PFNGLGETINTEGER64I_VPROC)load("glGetInteger64i_v");
	xwfgl_glGetBufferParameteri64v = (PFNGLGETBUFFERPARAMETERI64VPROC)load("glGetBufferParameteri64v");
	xwfgl_glFramebufferTexture = (PFNGLFRAMEBUFFERTEXTUREPROC)load("glFramebufferTexture");
	xwfgl_glTexImage2DMultisample = (PFNGLTEXIMAGE2DMULTISAMPLEPROC)load("glTexImage2DMultisample");
	xwfgl_glTexImage3DMultisample = (PFNGLTEXIMAGE3DMULTISAMPLEPROC)load("glTexImage3DMultisample");
	xwfgl_glGetMultisamplefv = (PFNGLGETMULTISAMPLEFVPROC)load("glGetMultisamplefv");
	xwfgl_glSampleMaski = (PFNGLSAMPLEMASKIPROC)load("glSampleMaski");
}
static int find_extensionsGL(void) {
	if (!get_exts()) return 0;
	(void)&has_ext;
	free_exts();
	return 1;
}

static void find_coreGL(void) {

    /* Thank you @elmindreda
     * https://github.com/elmindreda/greg/blob/master/templates/greg.c.in#L176
     * https://github.com/glfw/glfw/blob/master/src/context.c#L36
     */
    int i, major, minor;

    const char* version;
    const char* prefixes[] = {
        "OpenGL ES-CM ",
        "OpenGL ES-CL ",
        "OpenGL ES ",
        NULL
    };

    version = (const char*) glGetString(GL_VERSION);
    if (!version) return;

    for (i = 0;  prefixes[i];  i++) {
        const size_t length = strlen(prefixes[i]);
        if (strncmp(version, prefixes[i], length) == 0) {
            version += length;
            break;
        }
    }

/* PR #18 */
#ifdef _MSC_VER
    sscanf_s(version, "%d.%d", &major, &minor);
#else
    sscanf(version, "%d.%d", &major, &minor);
#endif

    GLVersion.major = major; GLVersion.minor = minor;
    max_loaded_major = major; max_loaded_minor = minor;
	XWFGL_GL_VERSION_1_0 = (major == 1 && minor >= 0) || major > 1;
	XWFGL_GL_VERSION_1_1 = (major == 1 && minor >= 1) || major > 1;
	XWFGL_GL_VERSION_1_2 = (major == 1 && minor >= 2) || major > 1;
	XWFGL_GL_VERSION_1_3 = (major == 1 && minor >= 3) || major > 1;
	XWFGL_GL_VERSION_1_4 = (major == 1 && minor >= 4) || major > 1;
	XWFGL_GL_VERSION_1_5 = (major == 1 && minor >= 5) || major > 1;
	XWFGL_GL_VERSION_2_0 = (major == 2 && minor >= 0) || major > 2;
	XWFGL_GL_VERSION_2_1 = (major == 2 && minor >= 1) || major > 2;
	XWFGL_GL_VERSION_3_0 = (major == 3 && minor >= 0) || major > 3;
	XWFGL_GL_VERSION_3_1 = (major == 3 && minor >= 1) || major > 3;
	XWFGL_GL_VERSION_3_2 = (major == 3 && minor >= 2) || major > 3;
	if (GLVersion.major > 3 || (GLVersion.major >= 3 && GLVersion.minor >= 2)) {
		max_loaded_major = 3;
		max_loaded_minor = 2;
	}
}

int xwfglLoadGLLoader(XWFGLloadproc load) {
	GLVersion.major = 0; GLVersion.minor = 0;
	glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
	if(glGetString == NULL) return 0;
	if(glGetString(GL_VERSION) == NULL) return 0;
	find_coreGL();
	load_GL_VERSION_1_0(load);
	load_GL_VERSION_1_1(load);
	load_GL_VERSION_1_2(load);
	load_GL_VERSION_1_3(load);
	load_GL_VERSION_1_4(load);
	load_GL_VERSION_1_5(load);
	load_GL_VERSION_2_0(load);
	load_GL_VERSION_2_1(load);
	load_GL_VERSION_3_0(load);
	load_GL_VERSION_3_1(load);
	load_GL_VERSION_3_2(load);

	if (!find_extensionsGL()) return 0;
	return GLVersion.major != 0 || GLVersion.minor != 0;
}

